name: Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: ${{ !env.ACT && 'npm' || '' }}

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run formatter'
        run: npm run format

  typecheck:
    runs-on: ubuntu-20.04

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: ${{ !env.ACT && 'npm' || '' }}

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run typechecker'
        run: npm run typecheck
